name: diabetic_nutrition
description: A therapeutic nutrition app for diabetic patients with accessibility features.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  sqflite: ^2.2.2
  path: ^1.8.3
  shared_preferences: ^2.0.17
  image_picker: ^0.8.6+1
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  vibration: ^1.7.6
  camera: ^0.10.3
  path_provider: ^2.0.12
  intl: ^0.17.0
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/foods.json
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
